In [10]:
#exemplo 2.1
symbols = "#$%¨&*"
result_code = [ord(symbol) for symbol in symbols]
result_code

[35, 36, 37, 168, 38, 42]

In [11]:
#exemplo 2.2
result_code = [ord(symbol) for symbol in symbols if ord(symbol) > 37]
result_code

[168, 38, 42]

In [12]:
#exemplo 2.3
result_code = list(filter(lambda c: c> 37, map(ord,symbols)))
result_code

[168, 38, 42]

In [13]:
#exemplo 2.4
colors = ["white", "black"]
sizes = ["S","M","L"]
result = [(color,size) for color in colors for size in sizes]
result

[('white', 'S'),
 ('white', 'M'),
 ('white', 'L'),
 ('black', 'S'),
 ('black', 'M'),
 ('black', 'L')]

In [14]:
#exemplo 2.5
import array

#by tuple
result_tuple = tuple(ord(symbol) for symbol in symbols)

#by array
result_array = array.array('I', (ord(symbol) for symbol in symbols))

In [15]:
#exemplo pessoal
def counter(palavra):
    vogal = ["a","e","i","o","u"]
    total_vogal = 0
    total_vogal += sum(palavra.count(x) for x in vogal)
    print(total_vogal)

In [16]:
counter("aeaeae")

6


In [17]:
#exemplo 2.6

colors = ["black", "white"]
sizes = ["s", "m", "l"]

for tshirt in ("%s %s" % (c,s) for c in colors for s in sizes):
    print(tshirt)

black s
black m
black l
white s
white m
white l


In [18]:
#exemplo 2.7
#tuples has registers

lat_cordinates = (65413.6874,-681.444)
name, age, weight = ("wesley", 15, 60)
travelers_id = [("CHI", 654741),("BRA", 797641),("USA", 478941)]

for travelers in travelers_id:
    print("{}/{}".format(*travelers))

CHI/654741
BRA/797641
USA/478941


In [19]:
latitude, longitude = lat_cordinates
latitude , longitude

(65413.6874, -681.444)

In [20]:
#exemplo 2.8
metro_areas = [ 
    ('Tokyo','JP',36.933,(35.689722,139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833)),]

print("{:15} | {:^9} | {:^9}".format("", "Latitude", "Longitude"))
fmt = "{:15} | {:9.4f} | {:9.4f}"
for name, cc, pop, (latitude, longitude) in metro_areas:
        print(fmt.format(name, latitude, longitude))

                | Latitude  | Longitude
Tokyo           |   35.6897 |  139.6917
Delhi NCR       |   28.6139 |   77.2089
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
Sao Paulo       |  -23.5478 |  -46.6358


In [21]:
#exemplo 2.9
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
print(tokyo)

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))


In [24]:
#exemplo 2.10
City._fields = ("City", "country", "population", "coordinates")
coordinate = namedtuple("latLong", "lat long")
rondonopolis = ("Rondonopolis", "BR", 19, coordinate(-23.547778, -46.635833, ))
result = City._make(rondonopolis)

for key, value in result._asdict().items():
    print(key + ":", value)

City: Rondonopolis
country: BR
population: 19
coordinates: latLong(lat=-23.547778, long=-46.635833)


In [ ]:
#exemplo 2.11


In [25]:
#exemplo 2.12

board = [["_"] * 3 for i in range(3)]
print(board)
board[0][2] = "X"
print(board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', 'X'], ['_', '_', '_'], ['_', '_', '_']]


In [4]:
#exemplo 2.13
invoice = """
0.....6.................................40........52...55........
1909  Pimoroni PiBrella                     $17.50    3    $52.50
1489  6mm Tactile Switch x20                 $4.95    2    $9.90
1510  Panavise Jr. - PV-201                 $28.00    1    $28.00
1601  PiTFT Mini Kit 320x240                $34.95    1    $34.95
"""

SKU = slice(0, 6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
    print(item[SKU], item[QUANTITY])

1909     3
1489     2
1510     1
1601     1
 


In [29]:
#exemplo 2.14
l = (1,2, [30,40])
l[2] += [50,60]
l

TypeError: 'tuple' object does not support item assignment

In [5]:
#exemplo 2.15
#forma errada de criar uma lista
weird_board = [['_'] * 3] * 3
weird_board
weird_board[1][2] = 'O'
weird_board

[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]

In [7]:
#exemplo 2.16
import dis
dis.dis('s[a] += b')

  1           0 LOAD_NAME                0 (s)
              2 LOAD_NAME                1 (a)
              4 DUP_TOP_TWO
              6 BINARY_SUBSCR
              8 LOAD_NAME                2 (b)
             10 INPLACE_ADD
             12 ROT_THREE
             14 STORE_SUBSCR
             16 LOAD_CONST               0 (None)
             18 RETURN_VALUE


In [30]:
#exemplo 2.17
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]
ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}'
def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * ' |' 
        print(ROW_FMT.format(needle, position, offset))

if __name__ == '__main__':
    if sys.argv[-1] == 'left':
        bisect_fn = bisect.bisect_left 
    else:
            bisect_fn = bisect.bisect
print('DEMO:', bisect_fn.__name__)
print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK)) 
demo(bisect_fn)

DEMO: bisect_right
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14     | | | | | | | | | | | | | |31
30 @ 14     | | | | | | | | | | | | | |30
29 @ 13     | | | | | | | | | | | | |29
23 @ 11     | | | | | | | | | | |23
22 @  9     | | | | | | | | |22
10 @  5     | | | | |10
 8 @  5     | | | | |8 
 5 @  3     | | |5 
 2 @  1     |2 
 1 @  1     |1 
 0 @  0    0 


In [31]:
#exemplo 2.18
def grade(score, breakpoints=[60, 70, 80, 90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

In [32]:
#exemplo 2.19
import bisect
import random
SIZE=7
random.seed(1729)
my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


In [8]:
#exemplo 2.20
from array import array
from random import random, seed

seed(10)

floats = array('d', (random() for i in range(10 ** 7)))

floats[-1]

with open('floats.bin', 'wb') as fp:
    floats.tofile(fp)

floats2 = array('d')

with open('floats.bin', 'rb') as fp:
    floats2.fromfile(fp, 10 ** 7)

floats2[-1]


0.8190492979077034

In [10]:
#exemplo 2.21
numbers = array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)
print(memv[0])
memv_oct = memv.cast('B')
memv_oct.tolist()
memv_oct[5] = 4
numbers

-2


array('h', [-2, -1, 1024, 1, 2])

In [15]:
#exemplo 2.22
import numpy as np

a = np.arange(12)
print(a)
print("--------------------------")
print(type(a))
print("--------------------------")
a.shape = 3, 4
print(a)
print("--------------------------")
print(a[2])
print("--------------------------")
print(a[2][1])
print("--------------------------")
print(a[:, 1])
print("--------------------------")
a.transpose()

[ 0  1  2  3  4  5  6  7  8  9 10 11]
--------------------------
<class 'numpy.ndarray'>
--------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------------
[ 8  9 10 11]
--------------------------
9
--------------------------
[1 5 9]
--------------------------


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [16]:
#exemplo 2.23
import collections

dq = collections.deque(range(10), maxlen=10)
print(dq)

dq.rotate(3)
print(dq)

dq.rotate(-4)
print(dq)

dq.appendleft(-1)
print(dq)

dq.extend([11, 22, 33])
print(dq)

dq.extendleft([10, 20, 30, 40])
print(dq)

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)
deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)
deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)
deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)
